### ISSUE TITLE
Schema check for metadata

### ISSUE THREAD

**Issue by jabrell** [jabrell/sweet_validation#19]
The registry should allow to set a metadata standard. The standard is enforced on each resource description. One possibility would be to describe the metadata using a table description that defines the constraints on the different fields allowed. 

E.g. consider the metadata specification
```yaml
name: metadata_schema
description: |
  Description of the metadata standard. The metadata section of all resource 
  description must comply
profile: tabular-data-resource  # Or "data-resource" for a more general resource

fields:
  - name: name
    type: string
    constraints:
      required: true
  - name: description
    type: string
    constraints:
      required: true
  - name: profile
    type: string
    constraints:
      enum: [tabular-data-resource, data-resource]
      required: true
  - name: created_by
    type: string
    constraints:
      required: true
  - name: tags
    type: array
    items:
      type: string
```

This can be used to check metadata section of resource schemes:

```yaml
name: generation
description: generation data
profile: tabular-data-resource
tags: [generation, electricity]
fields:
  - name: name
    type: string
  - name: year
    type: integer
  - name: value
    type: number
```

This would be invalid as the created_by field is missing. The next specification would however be valid:

```yaml
name: generation
description: generation data
profile: tabular-data-resource
created_by: User
fields:
  - name: name
    type: string
  - name: year
    type: integer
  - name: value
    type: number
```

Note that under frictionless v1 it is not possible, to restrict the fields to be only valid if stated in the table description (v2 seems to implement this). Therefore, we might consider enforcing this at the code level.
